language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r test-requirements.txt
  - pip install .
script:
  - py.test
after_success:
  - bash <(curl -s https://codecov.io/bash)
