language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
dist: xenial
sudo: true
install:
  - pip install -r test-requirements.txt
  - pip install --process-dependency-links .
script:
  - py.test
  - pycodestyle
after_success:
  - bash <(curl -s https://codecov.io/bash)
